# ansible-galaxy collection install ansible.posix
# ansible-galaxy collection install community.general
# ansible-galaxy collection install community.docker
# ansible-playbook -i inv install.yml
# ansible-galaxy collection install kubernetes.core
# inv: 
# [controller]
# server1 ansible_host=server ansible_ssh_private_key_file=/path.pem ansible_user=root

- name: Set AllowTcpForwarding in sshd_config
  hosts: all
  become: yes
  tasks:
    - name: Comment out AllowTcpForwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowTcpForwarding no'
        line: '#AllowTcpForwarding yes'

    - name: Restart sshd
      service:
        name: sshd
        state: restarted


- name: Update apt and install necessary packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ufw
        - docker.io
        - docker-compose
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - gnupg2
        - apt-transport-https
        - python3
        - python3-pip

- name: Install kubectl
  hosts: all
  become: yes
  tasks:
    - name: Create Kubernetes repository file
      copy:
        content: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
        dest: /etc/apt/sources.list.d/kubernetes.list
        owner: root
        group: root
        mode: '0644'

    - name: Add Kubernetes GPG key to APT keyring
      become: true
      apt_key:
        url: "https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key"
        state: present
        validate_certs: yes
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

- name: Install minikube
  hosts: all
  become: yes
  tasks:
    - name: Download minikube deb package
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
        dest: /tmp/minikube_latest_amd64.deb

    - name: Install minikube
      apt:
        deb: /tmp/minikube_latest_amd64.deb

- name: Add current user to docker group
  hosts: all
  become: true
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ ansible_env.SUDO_USER | default(ansible_env.USER) }}"
        groups: docker
        append: yes

- name: Setup UFW
  hosts: all
  become: yes
  tasks:
    - name: SSH
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
    - name: Enable UFW
      community.general.ufw:
        state: enabled

- name: Setup Kubernetes Cluster
  hosts: all
  become: no
  tasks:
    - name: Start Kubernetes Cluster
      command: minikube start

    - name: Install ansible helper python packages
      pip:
        name: kubernetes

    - name: Fetch traefik.yml from target machine
      copy:
        src: kubernetes/traefik.yml
        dest: /tmp/traefik.yml

    - name: Apply Traefik Deployment
      kubernetes.core.k8s:
        state: present
        definition: /tmp/traefik.yml