# ansible-galaxy collection install -r requirements.yml
# ansible-galaxy collection install ansible.posix
# ansible-galaxy collection install community.general
# ansible-galaxy collection install community.docker
# ansible-galaxy collection install kubernetes.core
# ansible-playbook -i inv install.yml
# inv: 
# [controller]
# server1 ansible_host=server ansible_ssh_private_key_file=/path.pem ansible_user=root

- name: Set AllowTcpForwarding in sshd_config
  hosts: all
  become: yes
  tasks:
    - name: Comment out AllowTcpForwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^AllowTcpForwarding no'
        line: '#AllowTcpForwarding yes'

    - name: Restart sshd
      service:
        name: sshd
        state: restarted


- name: Update apt and install necessary packages
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ufw
        - curl
        - python3
        - python3-pip

    - name: Install helm if not exists
      unarchive:
        src: https://get.helm.sh/helm-v3.14.4-linux-amd64.tar.gz
        dest: /usr/local/bin
        extra_opts: "--strip-components=1"
        owner: root
        group: root
        mode: 0755
        remote_src: true
      args:
        creates: /usr/local/bin/helm

    - name: Setup UFW
      community.general.ufw:
        rule: limit
        port: "{{ item }}"
        proto: tcp
        state: enabled
      loop:
        - 22
        - 80
        - 443

- name: Install k3s
  hosts: all
  become: yes
  tasks:
    - name: Run k3s installation script
      shell: curl -sfL https://get.k3s.io | sh -

- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
  tasks:
    - name: Install kubernetes Python package with --break-system-packages
      pip:
        name: kubernetes
        state: present
        extra_args: "--break-system-packages"
    
    - name: Add Nextcloud Helm repository
      kubernetes.core.helm_repository:
        name: nextcloud
        repo_url: https://nextcloud.github.io/helm/
        state: present

- name: Install Taefik
  hosts: all
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - name: Add Traefik Helm repository
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: https://traefik.github.io/charts

    - name: Update Helm chart repository
      kubernetes.core.helm_repository:
        name: traefik
        state: present
        repo_url: https://traefik.github.io/charts

    - name: Create namespace for Traefik
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: traefik
        state: present

    - name: Copy Values file to the remote host
      copy:
        src: kubernetes/traefik-values.yml
        dest: /tmp/traefik-values.yml

    - name: Copy Cloudflare credentials to the remote host
      copy:
        src: kubernetes/secrets/cloudflare-credentials.yml
        dest: /tmp/cloudflare-credentials.yml

    - name: Create Cloudflare credentials secret
      kubernetes.core.k8s:
        state: present
        definition: /tmp/cloudflare-credentials.yml

    - name: Install Traefik using Helm
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: kube-system
        release_name: traefik
        values_files:
          - /tmp/traefik-values.yml

- name: Install test Nextcloud instance
  hosts: all
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
    - name: Copy Nextcloud yaml to the remote host
      copy:
        src: kubernetes/nextcloud.yml
        dest: /tmp/nextcloud.yml

    - name: Create namespace for Nextcloud
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: nextdemand

    - name: Apply Nextcloud yaml
      kubernetes.core.k8s:
        state: present
        definition: /tmp/nextcloud.yml
        