apiVersion: batch/v1
kind: Job
metadata:
  name: nextcloud
  namespace: nextdemand
  labels:
    instanceId: test
spec:
  template:
    metadata:
      labels:
        app: nextcloud
        instanceId: test
    spec:
      containers:
      - name: nextcloud
        image: nextcloud
        # Add other configuration for the Nextcloud container
      restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: nextdemand
  labels:
    app: nextcloud
    instanceId: test
spec:
  selector:
    app: nextcloud
    instanceId: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  namespace: nextdemand
  name: nextcloud-stripprefix
spec:
  stripPrefixRegex:
    regex:
      - ^/[^/]+

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: nextdemand
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: nextdemand-nextcloud-stripprefix@kubernetescrd
spec:
  rules:
  - host: "nextdemand.neoin.space"
    http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: nextcloud-service
            port:
              number: 80


