job:
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: nextcloud
    namespace: nextdemand
    labels:
      instanceId: default
      app: nextcloud
  spec:
    template:
      metadata:
        labels:
          app: nextcloud
          instanceId: default
      spec:
        volumes:
          - name: nextcloud-config
            persistentVolumeClaim:
              claimName: nextcloud-config-pvc
        containers:
          - name: nextcloud
            image: nextcloud
            env:
              - name: NEXTCLOUD_ADMIN_USER
                value: "admin"
              - name: NEXTCLOUD_ADMIN_PASSWORD
                value: "default"
        initContainers:
          - name: nextcloud-init
            image: nextcloud
            command: >
              sh -c '
                  while [ ! -d "/var/www/html/data/admin/files/Photos/" ]; do
                    sleep 1
                  done
                  cp -r config/* /var/www/html/data/admin/files/Photos/'
            volumeMounts:
              - name: nextcloud-config
                mountPath: /config
        restartPolicy: Never

service:
  apiVersion: v1
  kind: Service
  metadata:
    name: nextcloud-service
    namespace: nextdemand
    labels:
      app: nextcloud
      instanceId: default
  spec:
    selector:
      app: nextcloud
      instanceId: default
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

ingress:
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: nextcloud-ingress
    namespace: nextdemand
    annotations:
      traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    labels:
      instanceId: default
      app: nextcloud
  spec:
    rules:
      - host: "default.nextdemand.neoin.space"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: nextcloud-service
                  port:
                    number: 80
