job:
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: nextcloud
    namespace: nextdemand
    labels:
      instanceId: default
      app: nextcloud
  spec:
    template:
      metadata:
        labels:
          app: nextcloud
          instanceId: default
      spec:
        containers:
          - name: nextcloud
            image: nextcloud
            # Add other configuration for the Nextcloud container
        restartPolicy: OnFailure

service:
  apiVersion: v1
  kind: Service
  metadata:
    name: nextcloud-service
    namespace: nextdemand
    labels:
      app: nextcloud
      instanceId: default
  spec:
    selector:
      app: nextcloud
      instanceId: default
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80

ingress:
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: nextcloud-ingress
    namespace: nextdemand
    labels:
      instanceId: default
      app: nextcloud
  spec:
    rules:
      - host: "default.nextdemand.neoin.space"
        http:
          paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: nextcloud-service
                  port:
                    number: 80
